import { useState, FormEvent } from 'react'
import { useTournamentsStore } from '@/stores/tournaments-store'
import { useCoursesStore } from '@/stores/courses-store'
import { useAuthStore } from '@/stores/auth-store'
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select'
import { AlertCircle } from 'lucide-react'

interface CreateTournamentDialogProps {
  open: boolean
  onOpenChange: (open: boolean) => void
}

export function CreateTournamentDialog({ open, onOpenChange }: CreateTournamentDialogProps) {
  const { createTournament, loading } = useTournamentsStore()
  const { courses } = useCoursesStore()
  const { user, userProfile } = useAuthStore()

  const [name, setName] = useState('')
  const [date, setDate] = useState('')
  const [courseId, setCourseId] = useState('')
  const [error, setError] = useState('')

  const handleSubmit = async (e: FormEvent) => {
    e.preventDefault()
    setError('')

    if (!name || !date || !courseId) {
      setError('Please fill in all required fields')
      return
    }

    if (!user || !userProfile) {
      setError('You must be logged in to create a tournament')
      return
    }

    try {
      await createTournament({
        name,
        date: new Date(date),
        courseId,
        affiliation: userProfile.affiliation,
        shotgunStart: false,
        state: 'Created',
        code: '', // Will be generated by the store
        createdBy: user.uid,
        createdAt: new Date(),
        lastUpdated: new Date(),
      })
      
      // Reset form
      setName('')
      setDate('')
      setCourseId('')
      onOpenChange(false)
    } catch (err: any) {
      setError(err.message || 'Failed to create tournament')
    }
  }

  const handleCancel = () => {
    setName('')
    setDate('')
    setCourseId('')
    setError('')
    onOpenChange(false)
  }

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-[500px]">
        <DialogHeader>
          <DialogTitle className="text-2xl">Create Tournament</DialogTitle>
          <DialogDescription>
            Add a new golf tournament to your organization
          </DialogDescription>
        </DialogHeader>

        <form onSubmit={handleSubmit}>
          <div className="space-y-4 py-4">
            {error && (
              <div className="flex items-center space-x-2 text-red-600 bg-red-50 p-3 rounded-lg">
                <AlertCircle className="w-5 h-5 flex-shrink-0" />
                <p className="text-sm font-medium">{error}</p>
              </div>
            )}

            <div className="space-y-2">
              <Label htmlFor="name" className="text-sm font-semibold">
                Tournament Name <span className="text-red-500">*</span>
              </Label>
              <Input
                id="name"
                placeholder="Enter tournament name"
                value={name}
                onChange={(e) => setName(e.target.value)}
                className="h-11"
                required
              />
            </div>

            <div className="space-y-2">
              <Label htmlFor="date" className="text-sm font-semibold">
                Date <span className="text-red-500">*</span>
              </Label>
              <Input
                id="date"
                type="date"
                value={date}
                onChange={(e) => setDate(e.target.value)}
                className="h-11"
                required
              />
            </div>

            <div className="space-y-2">
              <Label htmlFor="course" className="text-sm font-semibold">
                Course <span className="text-red-500">*</span>
              </Label>
              <Select value={courseId} onValueChange={setCourseId} required>
                <SelectTrigger className="h-11">
                  <SelectValue placeholder="Select a course" />
                </SelectTrigger>
                <SelectContent>
                  {courses.length === 0 ? (
                    <div className="p-2 text-sm text-slate-500">
                      No courses available. Create a course first.
                    </div>
                  ) : (
                    courses
                      .filter(course => course.affiliation === userProfile?.affiliation)
                      .map((course) => (
                        <SelectItem key={course.id} value={course.id}>
                          {course.name}
                        </SelectItem>
                      ))
                  )}
                </SelectContent>
              </Select>
            </div>
          </div>

          <DialogFooter className="gap-2">
            <Button
              type="button"
              variant="outline"
              onClick={handleCancel}
              disabled={loading}
            >
              Cancel
            </Button>
            <Button
              type="submit"
              disabled={loading}
              className="bg-gradient-to-r from-blue-600 to-blue-700"
            >
              {loading ? 'Creating...' : 'Create Tournament'}
            </Button>
          </DialogFooter>
        </form>
      </DialogContent>
    </Dialog>
  )
}

